name: tlc
base: core18
version: git
summary: TuneUp.ai Lightning Client
description: |
  This is the client of the fully automatic LightningCloud AI
  Performance Tuning Service, which tunes up the performance of your
  system by adjust parameters. The Client collects performance
  indicators from your system, sends them to LightningCloud for
  analysis, and sets system parameters according to LightningCloud's
  instructions.

grade: devel
confinement: devmode

parts:
  tlc:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt
    stage-packages:
      - collectd
      # The following packages are required by collectd
      - libcurl3-gnutls
      - libdevmapper-event1.02.1
      - libip6tc0
      - liblvm2app2.2
      - libperl5.26

apps:
  tlc:
    command: tlc

  tuclientd:
    command: tuclientd.py
    daemon: simple
    plugs:
      - network-bind
    
